name: Mirror CLI to sigscan-cli

on:
  push:
    branches: [ cli ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gstool@cli
        uses: actions/checkout@v4
        with:
          ref: cli
          fetch-depth: 0

      - name: Prepare mirror content
        run: |
          keep=(cli.py pyproject.toml MANIFEST.in README.md LICENSE analyzers core utils)
          shopt -s extglob
          for f in * .[^.]*; do
            case " ${keep[*]} " in
              *" ${f} "*) : ;;   # keep
              *) rm -rf "$f" || true ;;
            esac
          done

      - name: Configure SSH
        env:
          DEST_SSH_KEY: ${{ secrets.SIGSCAN_MIRROR_DEPLOY_KEY }}
        run: |
          install -m 700 -d ~/.ssh
          printf "%s" "$DEST_SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Trust GitHub host key
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"

      - name: Push to sigscan-cli@main
        run: |
          git init mirror
          rsync -a --delete --exclude .git ./ mirror/
          cd mirror
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Mirror from gstool@cli: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || true
          git branch -M main
          git remote add dest git@github.com:YOUR_ORG/sigscan-cli.git
          git push -f dest main
